export * from './AddValuesPage/AddValuesPage'
export * from './ChangeRolePage/ChangeRolePage'
export * from './ProductControlPage/ProductControlPage'
export * from './UserControlPage/UserControlPage'
export * from './AdminWelcomePage/AdminWelcomePage'