export * from './RegisterPage/RegisterPage'
export * from './ProductControlPage/ProductControlPage'
export * from './HomePage/HomePage'
export * from './LoginPage/LoginPage'
export * from './ActivatePage/ActivatePage'
export * from './RecoveryPage/RecoveryPage'
export * from './ChangePasswordPage/ChangePasswordPage'
export * from './NotFoundPage/NotFoundPage'
export * from './ProductDetailPage/ProductDetailPage'
export * from './UserPage/UserPage'
export * from './ValuesPage/ValuesPage'
export * from './UserControlPage/UserControlPage'
export * from './BasketPage/BasketPage'
export * from './ClientProductsPage/ClientProductsPage'
export * from './CommentListPage/CommentListPage'
export * from './CreateProductPage/CreateProductPage'
export * from './UpdateProductPage/UpdateProductPage'

